# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=30)),
                ('numero_interno', models.CharField(max_length=20)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('alto', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('largo', models.FloatField(blank=True, null=True)),
                ('valor_compra', models.FloatField()),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Dado De Baja'), ('R', 'En Reparacion'), ('D', 'Disponible'), ('AS', 'Asignado')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
